// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVVpwiA8MneesyEa7MoIpruGh2bceVmS8',
    appId: '1:999548562045:web:0aa5facd92c1b55d2cdf14',
    messagingSenderId: '999548562045',
    projectId: 'brain-boost-game',
    authDomain: 'brain-boost-game.firebaseapp.com',
    storageBucket: 'brain-boost-game.firebasestorage.app',
    measurementId: 'G-ML18FFDV9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq7Y4nql2CaX_Xgt3O3g_ArZWZZ81Vz3Y',
    appId: '1:999548562045:android:afceba2c70c525e22cdf14',
    messagingSenderId: '999548562045',
    projectId: 'brain-boost-game',
    storageBucket: 'brain-boost-game.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYbHESK9wghhMjjUA9wFv-nDXpRFAabB4',
    appId: '1:999548562045:ios:798b041a8f9305612cdf14',
    messagingSenderId: '999548562045',
    projectId: 'brain-boost-game',
    storageBucket: 'brain-boost-game.firebasestorage.app',
    iosBundleId: 'com.braingame.brainBoost',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYbHESK9wghhMjjUA9wFv-nDXpRFAabB4',
    appId: '1:999548562045:ios:798b041a8f9305612cdf14',
    messagingSenderId: '999548562045',
    projectId: 'brain-boost-game',
    storageBucket: 'brain-boost-game.firebasestorage.app',
    iosBundleId: 'com.braingame.brainBoost',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVVpwiA8MneesyEa7MoIpruGh2bceVmS8',
    appId: '1:999548562045:web:c3d1585b0b2f26dc2cdf14',
    messagingSenderId: '999548562045',
    projectId: 'brain-boost-game',
    authDomain: 'brain-boost-game.firebaseapp.com',
    storageBucket: 'brain-boost-game.firebasestorage.app',
    measurementId: 'G-DM2KYNMYRY',
  );
}
